### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000001",
  "amount": 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "7ea8f0cc7868462daa84726b1a98aeb4",
  "accountNumber": "1000000001",
  "amount": 30000
}

