### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 11,
  "accountNumber": "1000000000",
  "amount": 20000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "3c1b5a2dc4a7421ea4a7f52eb6d44da5",
  "accountNumber": "1000000002",
  "amount": 20000
}

### query transacion
GET http://localhost:8080/transaction/3c1b5a2dc4a7421ea4a7f52eb6d44da5
